2024-07-12 06:47:24,199 - signUpLogger - INFO - jk2nwrC8o7Q0GHLamUEZ3m1uRci1,pubsub+test0@email.com,-cqyfkrdi974, message id: 11712298150827556
AcknowledgeError when lease-modacking a message.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 1028, in _send_lease_modacks
    req.future.result()
  File "/usr/local/lib/python3.12/site-packages/google/cloud/pubsub_v1/subscriber/futures.py", line 125, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
google.cloud.pubsub_v1.subscriber.exceptions.AcknowledgeError: None AcknowledgeStatus.INVALID_ACK_ID

Exaplaination:
https://stackoverflow.com/questions/77138981/how-to-handle-acknowledging-a-pubsub-streampull-subscription-message